
<div class="div-table container-fluid well well-small">

    <!-- header -->
    <div class="div-table-header row-fluid">
        <div class="span2">Date</div>
        <div class="span2">Balance</div>
        <div class="span8">Transactions</div> 
    </div>

    <?php foreach($this->dates AS $dateKey=>$dateVal) : ?>
    
        <!-- content -->
        <div class="div-table-row row-fluid date <?php if ($this->todayKey==$dateKey) echo 'current'; ?>">

 
            <!-- Add Button / Date -->
            <div class='date-title span2'>
                <a class="btn btn-mini btn-success"  href="#">+</a>&nbsp;
                <?php echo date('jS M Y',$dateVal->unix); ?>
            </div>

            
            <!-- Balance -->
            <div class="date-balance span1 <?php echo $dateVal->balance==0 ? 'neutral' : $dateVal->balance>0 ? 'positive' : 'negative'; ?>">
                &pound; <?php echo $dateVal->balance; ?>
            </div>


            <!-- Transactions -->   
            <div class="date-transactions span9">
                <ul id="<?php echo $dateKey; ?>" class="unstyled">
                    <?php foreach ($dateVal->transactions AS $transKey=>$transVal) : ?>
                        <li id="<?php echo $transKey; ?>" class="clearfix">

                            <div class="span2 transaction-amount <?php echo $transVal->amount>0 ? 'positive' : 'negative'; ?>">                                
                                &pound;<input type="text" placeholder="0.00" value="<?php echo $transVal->amount; ?>" class="span10">
                            </div> 

                            <div class="span2 transaction-type"> 
                                <select class="span12">
                                    <?php foreach ($this->transactionTypes AS $typeKey=>$typeName) {
                                        $selected = $transVal->type==$typeKey ? 'selected="SELECTED"' : '';
                                        echo "<option id='$typeKey' $selected>$typeName</option>";
                                    } ?>
                                </select>
                            </div> 
                            
                            <div class="span2">
                                <?php echo $transVal->amount>0 ? 'payment from' : 'payment to'; ?>
                            </div>
                            
                            <div class="span2 transaction-account">                              
                                <select class="span12">
                                    <?php foreach ($this->accounts AS $accountKey=>$accountName) {
                                        $selected = $transVal->account==$accountKey ? 'selected="SELECTED"' : '';
                                        echo "<option id='$accountKey' $selected>$accountName</option>";
                                    } ?>
                                </select>
                            </div>



                            <div class="span2 transaction-tags">
                                <?php foreach($transVal->tags AS $tag) {                                    
                                    if (isset($this->transactionsTags[$tag])){
                                        echo "<span class='label'>{$this->transactionsTags[$tag]}</span>&nbsp;";
                                    }
                                 }?>
                            </div>

                            <?php if ($transVal->note!=='') : ?>                                
                                <div class="span2 transaction-note">  
                                    <textarea rows="3" class="span12"><?php echo $transVal->note; ?></textarea>                                    
                                </div> 
                            <?php endif; ?>

                        </li>
                    <?php endforeach; ?>
                </ul> 
            </div>
        </div>
    <?php endforeach; ?>
</div>


<script type='text/javascript'>
$(function() {
    $(".date-transactions ul").sortable({
        connectWith: ".date-transactions ul",
        opacity: 0.6, 
        cursor: 'move',
        update : function(e, ui) {
                var id = ui.item.attr('id');
                var to = $(this).attr('id');
                console.log('id: ' + id + ' to: ' + to);
                console.log('order: ')
                console.log($(this).children());
            }
    });
});
</script>

