

<div class="height-fill height-fill-locked row height-hidden">

    <!-- Header -->
    <div class="bgd-red span12">
        <div class="row">
            <div class="span2 bgd-green">1</div>
            <div class="span1 bgd-green">2</div>
            <div class="span1 bgd-green">3</div>
            <div class="span1 bgd-green">4</div>
            <div class="span1 bgd-green">5</div>
            <div class="span1 bgd-green">6</div>
            <div class="span1 bgd-green">7</div>
            <div class="span1 bgd-green">8</div>
            <div class="span1 bgd-green">9</div>
            <div class="span2 bgd-green">10</div>
        </div>
    </div>
    <!-- Header -->
    


    <!-- Content -->
    <div class="bgd-red span12 height-fill height-fill-locked height-scroll">
        <?php for($x=0;$x<500; $x++): ?>
            <div class="row">
                <div class="span2 bgd-blue"><?php echo $x; ?>::1</div>
                <div class="span1 bgd-blue">2</div>
                <div class="span1 bgd-blue">3</div>
                <div class="span1 bgd-blue">4</div>
                <div class="span1 bgd-blue">5</div>
                <div class="span1 bgd-blue">6</div>
                <div class="span1 bgd-blue">7</div>
                <div class="span1 bgd-blue">8</div>
                <div class="span1 bgd-blue">9</div>
                <div class="span2-scrollable bgd-blue">10</div>
            </div>
        <?php endfor; ?> 
    </div>
    <!-- Content -->

</div>

