<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headScript(); ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="<?php echo $this->baseUrl(); ?>"><?php echo Zend_Registry::get('env')->app->name; ?></a>
            <div class="nav-collapse collapse">
                <?php echo $this->Nav(array('ulClass'=>'nav'));?>
                <form class="navbar-search pull-right">
                    <input type="text" class="search-query" placeholder="Filter">
                </form>
            </div>
        </div>
      </div>
    </div>
        
    <div class="container">

        <?php 
        $messenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); 
        if ($messenger->hasCurrentMessages()): foreach($messenger->getCurrentMessages() AS $message): ?>
            <div class="alert <?php echo is_array($message) ? key($message) : ''; ?>">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <!--h4><?php echo is_array($message) ? strtolower(str_replace('alert-', '', key($message))) : 'alert';?>!</h4-->
                <?php echo is_array($message) ? current($message) : $message; ?>
            </div>
        <?php endforeach; endif; ?>

        <?php echo $this->layout()->content; ?>   

    </div> 



    </body>
</html>
        
