<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headScript(); ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        
        <div class="navbar navbar-inverse">            
            <div class="navbar-inner container">
                <a class="brand" href="<?php echo $this->baseUrl(); ?>"><?php echo Zend_Registry::get('env')->app->name; ?></a>
            </div>            
        </div>
        
        <div class="container-fluid">


            <div class="row-fluid">

                <div class="span2">
                    <?php echo $this->Nav(array('ulClass'=>'well well-large nav nav-list'));?>
                </div>


                <div class="span10">        

                    <?php 
                    $messenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); 
                    if ($messenger->hasCurrentMessages()): foreach($messenger->getCurrentMessages() AS $message): ?>

                        <div class="alert <?php echo is_array($message) ? key($message) : ''; ?>">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <!--h4><?php echo is_array($message) ? strtolower(str_replace('alert-', '', key($message))) : 'alert';?>!</h4-->
                            <?php echo is_array($message) ? current($message) : $message; ?>
                        </div>
                    <?php endforeach; endif; ?>


                    <!--div class="well well-large"-->                    
                        <?php echo $this->layout()->content; ?>                   
                    <!--/div-->  

                </div>

                <!--div class="progress progress-striped active">
                    <div class="bar" style="width: 100%;"></div>                
                </div-->

            </div>
        </div>
    </body>
</html>
        
